Team4_SELT2020-main/config/routes.rb
Rails.application.routes.draw do

  resources :cards, :tables, :users, :sessions
  post 'cards/play_card'
  post 'cards/draw_card'
  post 'cards/reset_card'
  post 'cards/reset_game'
  post 'cards/select_card'
  post 'cards/pass_card'
  post 'cards/recard_card'
  post 'cards/take_from_board'
  post 'cards/leave_game'
  post 'cards/discard_card'
  post 'cards/recover_discard'
  root 'tables#index'
  post 'users/assign_current_user_table'
  post 'cards/discard_cards'
  get 'cards/discard_cards'
  post 'cards/cards_to_discard'
  get 'cards/remove_cards'
  post 'cards/cards_to_remove'
  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete

end

Team4_SELT2020-main/app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous"></link>
    <title>Team4Selt2020FinalProject</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <body>
      <div class="navbar navbar-dark bg-dark text-white">
        <h2 class="title">ACES</h2>
          <%if !@current_user%>
            <%= button_to "Sign up/Login", login_path, :id => 'signupLogin' ,:method => :get %>
          <%else %>
            <p class="message" id="notice">
              You are logged in as <%= @current_user.name%>
            </p>
            <%= button_to "Logout", logout_path, :id => 'logout' , :method => :delete%>
          <%end %>



      </div>
      <div class="container">
        <div class="main">
        </div>
          <br>
          <%= yield %>
        </div>
      </div>
    </body>
  </head>

</html>