Team4_SELT2020-main/config/routes.rb
Rails.application.routes.draw do

  resources :cards, :tables, :users, :sessions
  post 'cards/play_card'
  post 'cards/draw_card'
  post 'cards/reset_card'
  post 'cards/reset_game'
  post 'cards/select_card'
  post 'cards/pass_card'
  post 'cards/recard_card'
  post 'cards/take_from_board'
  post 'cards/leave_game'
  post 'cards/discard_card'
  post 'cards/recover_discard'
  root 'tables#index'
  post 'users/assign_current_user_table'
  post 'cards/discard_cards'
  get 'cards/discard_cards'
  post 'cards/cards_to_discard'
  get 'cards/remove_cards'
  post 'cards/cards_to_remove'
  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete

end

Team4_SELT2020-main/app/controllers/tables_controller.rb
class TablesController < ApplicationController
  def home
  end
  def table_params
    params.require(:table).permit(:tablename)
  end
  def show
    id = params[:id] # retrieve movie ID from URI route
    @table = Table.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end
  def create
    x = table_params
    if Table.where(tablename: x.values.first).exists?
      flash[:warning]="Please try a unique table name, look through the page and see the table names and dont use them"
      redirect_to new_table_path
    else
      @table=Table.create!(table_params)
      @user = User.where(name: @current_user.name).first
      @user.update(tablename: x["tablename"])
      @current_user.update(tablename: x["tablename"])
      redirect_to new_card_path(request.parameters)
    end
  end
  def destroy
    @table = Table.find(params[:id])
    t1 = @table.tablename
    @table.destroy
    @cards = Card.where(tablename:t1)
    @cards.each do |card|
      card.destroy
    end
    redirect_to tables_path
  end
  def index
    @tables = Table.all
  end

  def new
    # default: render 'new' template
  end
end

Team4_SELT2020-main/app/views/tables/index.html.erb
<%= stylesheet_link_tag 'application'  %>

<!--  This file is app/views/movies/index.html.erb -->
<%if !@current_user%>
  <h1>Welcome to Aces!</h1>
  <h3>Please Login to begin.</h3>
  <center><%= button_to "Sign up/Login", login_path, :id => 'signupLogin' ,:method => :get %></center>
<%else %>
<h1>All Games</h1>
<table class="table table-striped col-md-12" id="movies">
  <thead>
  <tr>
    <th>Table Name</th>
    <th>Enter Game</th>
    <th>Delete Table?</th>
  </tr>
  </thead>
  <tbody>
  <%count = 0 %>
  <% @tables.each do |table| %>
    <tr>
      <td>
        <%=table.tablename %>
      </td>
      <td>
        <% if table.tablename == @current_user.tablename %>
          <%= form_tag cards_path, :id => "gameBoard", method: :get%>
            <%=submit_tag "Enter Game",name: table.tablename %>
          <%end %>
      </td>
      <td>
        <%= link_to "Delete table", table_path(table), :class => 'btn btn-primary' %>
      </td>
  <%end %>
    </tr>
  </tbody>
  <%=link_to 'Add new Game', new_table_path, :class => 'btn btn-primary' %>
</table>
  <%= link_to "Choose Table", user_path(User.where(name: @current_user.name).first, @tables), :class => 'btn btn-primary' %>
<%end %>

Team4_SELT2020-main/app/views/tables/new.html.erb
<%= stylesheet_link_tag 'application'  %>

<h1>Create New Table</h1>
<% if flash[:notice] %>
  <div class="alert alert-danger">
    <div class="message" id="notice">
      <%= flash[:notice] %>
    </div>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger">
    <div class="flashMessage" id="warning">
      <%= flash[:warning] %>
    </div>
  </div>
<% end %>
<%= form_tag tables_path, :class => 'form' do %>
  <%  cards = [{ name: "AS", location: "deck", status: 1, cardFront: "&#127137", tablename: 'tempTable'},
               { name: "2S", location: "deck", status: 1, cardFront: "&#127138", tablename: 'tempTable'},
               { name: "3S", location: "deck", status: 1, cardFront: "&#127139", tablename: 'tempTable'},
               { name: "4S", location: "deck", status: 1, cardFront: "&#127140", tablename: 'tempTable'},
               { name: "5S", location: "deck", status: 1, cardFront: "&#127141", tablename: 'tempTable'},
               { name: "6S", location: "deck", status: 1, cardFront: "&#127142", tablename: 'tempTable'},
               { name: "7S", location: "deck", status: 1, cardFront: "&#127143", tablename: 'tempTable'},
               { name: "8S", location: "deck", status: 1, cardFront: "&#127144", tablename: 'tempTable'},
               { name: "9S", location: "deck", status: 1, cardFront: "&#127145", tablename: 'tempTable'},
               { name: "10S", location: "deck", status: 1, cardFront: "&#127146", tablename: 'tempTable'},
               { name: "JS", location: "deck", status: 1, cardFront: "&#127147", tablename: 'tempTable'},
               { name: "QS", location: "deck", status: 1, cardFront: "&#127149", tablename: 'tempTable'},
               { name: "KS", location: "deck", status: 1, cardFront: "&#127150", tablename: 'tempTable'},
               { name: "AH", location: "deck", status: 1, cardFront: "&#127153", tablename: 'tempTable'},
               { name: "2H", location: "deck", status: 1, cardFront: "&#127154", tablename: 'tempTable'},
               { name: "3H", location: "deck", status: 1, cardFront: "&#127155", tablename: 'tempTable'},
               { name: "4H", location: "deck", status: 1, cardFront: "&#127156", tablename: 'tempTable'},
               { name: "5H", location: "deck", status: 1, cardFront: "&#127157", tablename: 'tempTable'},
               { name: "6H", location: "deck", status: 1, cardFront: "&#127158", tablename: 'tempTable'},
               { name: "7H", location: "deck", status: 1, cardFront: "&#127159", tablename: 'tempTable'},
               { name: "8H", location: "deck", status: 1, cardFront: "&#127160", tablename: 'tempTable'},
               { name: "9H", location: "deck", status: 1, cardFront: "&#127161", tablename: 'tempTable'},
               { name: "10H", location: "deck", status: 1, cardFront: "&#127162", tablename: 'tempTable'},
               { name: "JH", location: "deck", status: 1, cardFront: "&#127163", tablename: 'tempTable'},
               { name: "QH", location: "deck", status: 1, cardFront: "&#127165", tablename: 'tempTable'},
               { name: "KH", location: "deck", status: 1, cardFront: "&#127166", tablename: 'tempTable'},
               { name: "AD", location: "deck", status: 1, cardFront: "&#127169", tablename: 'tempTable'},
               { name: "2D", location: "deck", status: 1, cardFront: "&#127170", tablename: 'tempTable'},
               { name: "3D", location: "deck", status: 1, cardFront: "&#127171", tablename: 'tempTable'},
               { name: "4D", location: "deck", status: 1, cardFront: "&#127172", tablename: 'tempTable'},
               { name: "5D", location: "deck", status: 1, cardFront: "&#127173", tablename: 'tempTable'},
               { name: "6D", location: "deck", status: 1, cardFront: "&#127174", tablename: 'tempTable'},
               { name: "7D", location: "deck", status: 1, cardFront: "&#127175", tablename: 'tempTable'},
               { name: "8D", location: "deck", status: 1, cardFront: "&#127176", tablename: 'tempTable'},
               { name: "9D", location: "deck", status: 1, cardFront: "&#127177", tablename: 'tempTable'},
               { name: "10D", location: "deck", status: 1, cardFront: "&#127178", tablename: 'tempTable'},
               { name: "JD", location: "deck", status: 1, cardFront: "&#127179", tablename: 'tempTable'},
               { name: "QD", location: "deck", status: 1, cardFront: "&#127181", tablename: 'tempTable'},
               { name: "KD", location: "deck", status: 1, cardFront: "&#127182", tablename: 'tempTable'},
               { name: "AC", location: "deck", status: 1, cardFront: "&#127185", tablename: 'tempTable'},
               { name: "2C", location: "deck", status: 1, cardFront: "&#127186", tablename: 'tempTable'},
               { name: "3C", location: "deck", status: 1, cardFront: "&#127187", tablename: 'tempTable'},
               { name: "4C", location: "deck", status: 1, cardFront: "&#127188", tablename: 'tempTable'},
               { name: "5C", location: "deck", status: 1, cardFront: "&#127189", tablename: 'tempTable'},
               { name: "6C", location: "deck", status: 1, cardFront: "&#127190", tablename: 'tempTable'},
               { name: "7C", location: "deck", status: 1, cardFront: "&#127191", tablename: 'tempTable'},
               { name: "8C", location: "deck", status: 1, cardFront: "&#127192", tablename: 'tempTable'},
               { name: "9C", location: "deck", status: 1, cardFront: "&#127193", tablename: 'tempTable'},
               { name: "10C", location: "deck", status: 1, cardFront: "&#127194", tablename: 'tempTable'},
               { name: "JC", location: "deck", status: 1, cardFront: "&#127195", tablename: 'tempTable'},
               { name: "QC", location: "deck", status: 1, cardFront: "&#127197", tablename: 'tempTable'},
               { name: "KC", location: "deck", status: 1, cardFront: "&#127198", tablename: 'tempTable'},
               { name: "RJ", location: "deck", status: 1, cardFront: "&#127167", tablename: 'tempTable'},
               { name: "BJ", location: "deck", status: 1, cardFront: "&#127183", tablename: 'tempTable'},]%>

  <%= label :table, :tablename, 'Table Name', :class => 'col-form-label' %>
  <%= text_field :table, :tablename, :class => 'form-control' %>
  <%= label :table, :included, 'Cards to be exluded (for a normal deck check the two jokers at the bottom)', :class => 'col-form-label' %>
  <table class="table table-striped col-md-12 table-condensed cf" id="cards">
    <thead>
    <tr>
      <th>Card</th>
      <th>Name</th>
      <th>Select</th>
    </tr>
    </thead>
    <tbody>
    <% cards.each do |card| %>
      <tr>
        <td>
          <%= card[:cardFront].html_safe %>
        </td>
        <td>
          <%= card[:name] %>
        </td>
        <td>
          <%= check_box_tag "checkbox[#{card[:name]}]"%>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
  <br/>
  <%= submit_tag 'Save Changes', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', tables_path, :class => 'btn btn-secondary' %>
<% end %>

Team4_SELT2020-main/app/views/tables/show.html.erb
<%= link_to 'Delete', table_path(@table), 'data-method' => 'delete', 'data-confirm' => 'Are you sure?', :class => 'btn btn-danger col-2' %>