Team4_SELT2020-main/config/routes.rb
Rails.application.routes.draw do

  resources :cards, :tables, :users, :sessions
  post 'cards/play_card'
  post 'cards/draw_card'
  post 'cards/reset_card'
  post 'cards/reset_game'
  post 'cards/select_card'
  post 'cards/pass_card'
  post 'cards/recard_card'
  post 'cards/take_from_board'
  post 'cards/leave_game'
  post 'cards/discard_card'
  post 'cards/recover_discard'
  root 'tables#index'
  post 'users/assign_current_user_table'
  post 'cards/discard_cards'
  get 'cards/discard_cards'
  post 'cards/cards_to_discard'
  get 'cards/remove_cards'
  post 'cards/cards_to_remove'
  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete

end

Team4_SELT2020-main/app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :table
end

Team4_SELT2020-main/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :set_current_user
  def new
  end

  def create
    if Card.where(tablename: params[:commit]).exists?
      redirect_to tables_path
    else
      raise "Something is wrong with the db"
    end
  end
  def show
    id = params[:id]
    if id == 'discard_cards'
      @cards = Card.where(tablename: @current_user.tablename).order(location: :asc)
      render cards_discard_cards_path
    elsif id == 'remove_cards'
      @cards = Card.where(tablename: @current_user.tablename).order(location: :asc)
      render cards_remove_cards_path
    else
      @card = Card.find(id)
    end
  end
  def index
    @cards=Card.where(tablename: @current_user.tablename)
    @cards.each_with_index do |card, indexs|
      if card[:location] == "deck" and card[:status] == 1
        Card.find(card[:id]).update(location: 'GameDeck')
      end
    end
  end
  def take_from_board
    a = self.params[:commit]
    change = Card.where(cardFront: a, tablename: @current_user.tablename)
    change.each do |card|
      if card.status == 4
        Card.find(card.id).update(status: 3, location: @current_user.name)
        flash[:warning]="Card taken by #{@current_user.name}"
      else
        flash[:warning]="No Card Found"
      end
    end
    redirect_to cards_path
  end
  def play_card
    a = self.params[:commit]
    change = Card.where(cardFront: a, location: @current_user.name, tablename: @current_user.tablename)
    change.each do |card|
      if card.status == 3 and card.location == @current_user.name
        Card.find(card.id).update(status: 4)
        flash[:notice]="Card played"
      elsif card.status == 2 and card.location == @current_user.name
        Card.find(card.id).update(status: 3)
        flash[:notice]="Card played"
      else
        flash[:warning]="Card not played"
      end
    end
    redirect_to cards_path
  end
  def reset_card
    @cards=Card.where(tablename: @current_user.tablename).where.not(status:0)
    @cards.find_each do |card|
      unless card.status == 0
        if card.name == 'RJ' or card.name == 'BJ'
          Card.find(card.id).update(location: "deck", status: 0)
        else
          Card.find(card.id).update(location: "deck", status: 1)
        end
      end
    end
    flash[:warning] = "reset deck"
    redirect_to cards_path
  end
  def recover_discard
    @cards=Card.where(tablename: @current_user.tablename, status:5)
    @cards.find_each do |card|
      Card.find(card.id).update(status:1)
    end
    flash[:warning]="Discarded Cards Recovered"
    redirect_to cards_path
  end
  def recard_card
    count = 0
    movement = params[:move][:movement]
    case movement
    when 'Board to Action'
      Card.where(location: @current_user.name, status: 4, tablename: @current_user.tablename).find_each do |card|
        Card.find(card.id).update(status: 3)
        count +=1
      end
    when 'Action to Hand'
      Card.where(location: @current_user.name,status: 3, tablename: @current_user.tablename).find_each do |card|
        Card.find(card.id).update(status: 2)
        count +=1
      end
    when 'Hand to Assigned Deck'
      Card.where(location: @current_user.name,status: 2, tablename: @current_user.tablename).find_each do |card|
        Card.find(card.id).update(status: 1)
        count +=1
      end
    end
    if count !=0
      flash[:warning]="recard"
      redirect_to cards_path
    else
      flash[:warning]="No recard happened"
      redirect_to cards_path
    end
  end
  def discard_card
    discard_params= params[:move][:movement]
    case discard_params
    when "Me"
      if params[:commit] != 'a'
      Card.where(status: 3, tablename: @current_user.tablename).find_each do |card|
        Card.find(card.id).update(location: @current_user.name, status: 5)
      end
      flash[:warning]="Discarded Action to Me"
      redirect_to cards_path
      else
      Card.where(status: 4, tablename: @current_user.tablename).find_each do |card|
        Card.find(card.id).update(location: @current_user.name, status: 5)
      end
      flash[:warning]="Discarded to Me"
      redirect_to cards_path
      end
      when "Unassigned"
      if params[:commit] != 'a'
        Card.where(status: 3, tablename: @current_user.tablename).find_each do |card|
        Card.find(card.id).update(location: 'GameDeck', status: 5)
        end
        flash[:warning]="Discarded Action to Unassigned"
        redirect_to cards_path
        else
      Card.where(status: 4, tablename: @current_user.tablename).find_each do |card|
        Card.find(card.id).update(location: 'GameDeck', status: 5)
      end
      flash[:warning]="Discarded to Unassigned"
      redirect_to cards_path
    end
    end
    end
  def pass_card
    @cards=Card.where(tablename: @current_user.tablename)
    @to = params[:to]
    count =0
    @from = @current_user.name
    @cards.find_each do |card|
      if card.status == 3 and card.location == @from#if card is in action
        count +=1
        Card.find(card.id).update(location: @to, status: 2)
      end
    end
    if count != 0
      flash[:warning]="Card(s) passed"
      redirect_to cards_path
    else
      flash[:warning]="Card(s) not passed"
      redirect_to cards_path
  end
    end
  def draw_card
    if params[:commit] == "Draw"
      get_shuffled_deck
      count =0
      @cards.each do |card|
      if card[:status] == 1
        if card.location == @current_user.name
          Card.find(card.id).update(status: 2)
          flash[:notice] = "Card added to #{@current_user.name}"
          count +=1
          break
        elsif card[:location] == 'GameDeck'
          Card.find(card[:id]).update(status: 2, location: @current_user.name)
          flash[:notice] = "Card added to #{@current_user.name}"
          count +=1
          break
        end
      end
      end
      if count == 0
        flash[:warning] = "decks empty"
      end
    else
      card = Card.where(status:1, location: 'GameDeck', tablename: @current_user.tablename).shuffle
      if !card.first.nil?
        card.first.update(status:4, location: 'Dealer')
      else
        flash[:warning] = "decks empty"
      end
    end
    redirect_to cards_path
  end
  def select_card
    @cards = Card.where(tablename: @current_user.tablename)
    card_val = params[:card_select]
    @cards.where(name: card_val).find_each do |card|
      Card.find(card.id).update!(location: @current_user.name, status: 2)
    end
    flash[:notice]="Selected card placed in user hand"
    redirect_to cards_path
  end
  def cards_to_discard
    if(params[:checkbox].nil?)
      flash[:warning] = "No cards selected"
      redirect_to cards_path
    else
      key_arr = params[:checkbox].keys
      key_arr.each do |id|
        card = Card.find_by(id: id)
        card.update!(location: 'discard', status: 5)
      end
      redirect_to cards_path

     end
  end
  def cards_to_remove
    if(params[:checkbox].nil?)
      flash[:warning] = "No cards selected"
      redirect_to cards_path
    else
      key_arr = params[:checkbox].keys
      key_arr.each do |id|
        card = Card.find_by(id: id)
        card.update!(location: 'Out of Play', status: 0)
      end
      redirect_to cards_path
    end
  end
  def leave_game
    redirect_to root_path
  end

  def get_shuffled_deck
    @cards=Card.where(tablename: @current_user.tablename).shuffle
  end
end

Team4_SELT2020-main/app/views/cards/discard_cards.html.erb
<h1>Which card(s) would you like to discard?</h1>
<%= form_tag cards_cards_to_discard_path do %>

  <table class="table table-striped col-md-12" id="cards">
    <thead>
      <tr>
        <th>Card</th>
        <th>Location</th>
        <th>Select</th>
      </tr>
    </thead>
    <tbody>
      <% @cards.each do |card| %>
        <tr>
          <td>
            <p style="font-size: 4em"> <%= card.cardFront.html_safe %></p>
          </td>
          <td>
            <%= card.location %>
          </td>
          <td>
            <%= check_box_tag "checkbox[#{card[:id]}]" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <%= submit_tag 'Discard card(s)', :id => 'cards_button', :class => 'btn btn-primary' %>
  <%= link_to 'Return to game', cards_path, :class => 'btn btn-primary' %>
<% end %>

Team4_SELT2020-main/app/views/cards/index.html.erb
<%= stylesheet_link_tag 'application'  %>


<html>
    <div class = 'grid-container'>
      <header1>
       <h1>Current Lobby: <%= @current_user.tablename %></h1>

      </header1>
      <header1>
        <%=form_tag(cards_discard_card_path(:commit => "a"),method: :post,name: 'discard_card', :remote=> true) do%>
          <div class="secondary btn pretty"><%= label :discard, "Discard?"%></div>
          <div class="secondary btn pretty"><%= select :move, :movement, ["Unassigned","Me"]%></div>
          <div class="secondary btn pretty"><%= submit_tag 'Discard'%></div>
        <%end%>
      </header1>
      <header2>
        <% if flash[:notice] %>
          <div class="alert alert-danger">
            <div class="message" id="notice">
              <%= flash[:notice] %>
            </div>
          </div>
        <% elsif flash[:warning] %>
          <div class="alert alert-danger">
            <div class="flashMessage" id="warning">
              <%= flash[:warning] %>
            </div>
          </div>
        <% end %>
      </header2>
  <body>
  <section>
    <h5><%="#{@current_user.name}'s In Play Hand"%></h5>
    <%z = @cards.where(location: @current_user.name, status: 4, tablename: @current_user.tablename).sort %>
    <% z.each do |card| %>
      <% if card.location == @current_user.name and card.status ==4%>
        <%=link_to "#{card.cardFront}".html_safe, cards_take_from_board_path(:commit => "#{card.cardFront}".html_safe), method: :post %>
      <% end %>
    <% end %>
  </section>

  <div class ="section2">
    <h5>Opponent's in Play Hand</h5>
    <%x = Card.where(status: 4, tablename: @current_user.tablename)%>
    <%x=x.where.not(location: @current_user.name) %>
    <%a = x.uniq.pluck(:location)%>
    <%if a.include?('Dealer')%>
      <%a -= ['Dealer'] %>
      <% a = ['Dealer'] + a %>
    <% end %>
    <%h = Hash.new %>
    <%a.each do |c| %>
      <% unless c == @current_user.name %>
        <%h[c] = x.where(location: c) %>
        <%end %>
    <%end %>
    <%h.each do |key, value| %>
        <h5><%="#{key}" %></h5>
        <%value.sort %>
        <% value.each do |card| %>
          <%=link_to "#{card.cardFront}".html_safe, cards_take_from_board_path(:commit => "#{card.cardFront}".html_safe), method: :post %>
        <% end %>
        <%end %>
      <br><br>

  </div>
  <div class ="section3">
    <h4>Dealer</h4>
    <%=link_to "&#127136".html_safe, cards_draw_card_path(commit: "Deal"), method: :post %>
  </div>
  <div class = "section4">
  <div class ="hand">
    <h4>Other Players Hands</h4>
    <%listOfPlayers = Hash.new %>
    <% @cards.each do |card| %>
      <% if card.location != "GameDeck" and (card.status == 2 or card.status == 3) and card.location != "deck" and card.location != @current_user.name and card.tablename == @current_user.tablename%>
        <%if listOfPlayers.has_key?("#{card.location}") %>
          <%listOfPlayers["#{card.location}"] = listOfPlayers.fetch("#{card.location}") + 1 %>
        <%else %>
          <% listOfPlayers["#{card.location}"] = 1%>
        <%end %>
      <%end%>
    <%end%>
    <% listOfPlayers.each_pair do |key, value| %>
      <%= key%>
      <% (0..value-1).each do  %>
        &#127136
      <%end %>
      <br>
    <% end %>
  </div>
  </div>
    <aside>
      <div class = "draw">
      &#128104
        <%=link_to "&#127136".html_safe, cards_draw_card_path(commit: "Draw"), method: :post %>
      </div>
      <div class = "select">
        <%=form_tag({:action=> 'select_card'}, method: :post, name: 'card_select', :remote => true) do%>
          <div class="secondary btn pretty"><%= label :card_select, 'Specific Card?' %></div>
          <div class="secondary btn pretty"><%= select_tag(:card_select, options_from_collection_for_select(@cards, :name, :name), multiple: false) %></div>
          <div class="secondary btn pretty"><%= submit_tag 'Select'%></div>
        <%end%>
      </div>
    </aside>
      <main>
        <div class = "hand">
          <h4><%="#{@current_user.name}'s Hand"%></h4>
          <% @cards = @cards.where(tablename: @current_user.tablename).sort %>
          <% @cards.each do |card| %>
            <% if card.location == @current_user.name and card.status ==2%>
              <%=link_to "#{card.cardFront}".html_safe, cards_play_card_path(:commit => "#{card.cardFront}".html_safe), method: :post %>
            <%end%>
          <%end%>

        </div>
      </main>
  <main>
    <div class = "hand">
      <h4><%="#{@current_user.name}'s Action Area"%></h4>
      <%counter = 0 %>
        <% @cards.each do |card| %>
          <% if card.location == @current_user.name and card.status ==3%>
            <%=link_to "#{card.cardFront}".html_safe, cards_play_card_path(:commit => "#{card.cardFront}".html_safe), method: :post %>
            <%counter+=1 %>
          <%end%>
        <%end%>
        <%if counter==0%>
         <!-- &#127136 -->
        <%end%>
    </div>


  </main>
  <p class="extra3"></p>
  <h3 class="extra2">Player actions</h3>
  <p class="extra3"></p>
  <div class = "extra">
      <%=form_tag({:action=> 'recard_card'},method: :post,name: 'recard_card', :remote=> true) do%>
        <div class="secondary btn pretty"><%= label :move, :movement, 'Move?' %></div>
        <div class="secondary btn pretty"><%= select :move, :movement, ["Action to Hand","Board to Action","Hand to Assigned Deck"]%></div>
        <div class="secondary btn pretty"><%= submit_tag 'Move'%></div>
      <%end%>
  </div>
  <div class="extra">
    <%=form_tag({:action=> 'recover_discard'},method: :post, :remote=> true) do%>
      <div class="secondary btn pretty"><%= submit_tag 'Recover Discard'%></div>
      <% end %>
    <%=link_to 'Discard', cards_discard_cards_path(:sort => 'location'), :id => 'discard_link' %>
    <%=link_to 'Remove Cards', cards_remove_cards_path(:sort => 'location'), :id => 'remove_link' %>
  </div>
  <div class = "extra">

    <%=form_tag({:action=> 'pass_card'},method: :post,name: 'pass_card', :remote=> true) do%>
      <div class="secondary btn pretty"><%= label :to, 'Pass action cards to: ' %></div>
          <div class="secondary btn pretty"><%= select_tag(:to, options_for_select(User.where(tablename: @current_user.tablename).uniq.pluck(:name)), multiple: false) %></div>
        <div class="secondary btn pretty"><%= submit_tag 'Pass'%></div>
    <%end%>
  </div>
  <div class="extra">
    <%=form_tag(cards_discard_card_path(:commit => "b"),method: :post,name: 'discard_card', :remote=> true) do%>
      <div class="secondary btn pretty"><%= label :discard, "Discard?"%></div>
      <div class="secondary btn pretty"><%= select :move, :movement, ["Unassigned","Me"]%></div>
      <div class="secondary btn pretty"><%= submit_tag 'Discard'%></div>
    <%end%>
  </div>
  <footer><div></div></footer>
  <footer><div></div></footer>

  <footer>
    <%=form_tag({:action=> 'leave_game'},method: :post,name: 'leave_game', :remote=> true) do%>
      <div class="secondary btn pretty"><%= submit_tag 'Leave Game'%></div>
    <%end%>
  </footer>
  <footer><div></div></footer>
  <footer><div></div></footer>
  <footer><div></div></footer>
  <footer><div></div></footer>
  <footer><div></div></footer>
  <footer><div></div></footer>
  <footer>
    <%=form_tag({:action=> 'reset_card'},method: :post,name: 'reset_card', :remote=> true) do%>
      <div class="secondary btn pretty"><%= submit_tag 'Reset Game'%></div>
    <%end%>
  </footer>
  <footer><div></div></footer>
  <footer><div></div></footer>
  <script>
      window.addEventListener("DOMContentLoaded", function() {
          setInterval(function(){
              location.reload();
          }, 15000);
      });
  </script>
  </body>
  </div>
</html>

Team4_SELT2020-main/app/views/cards/new.html.erb
<%= stylesheet_link_tag 'application'  %>
<% if flash[:notice] %>
  <div class="alert alert-danger">
    <div class="message" id="notice">
      <%= flash[:notice] %>
    </div>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger">
    <div class="flashMessage" id="warning">
      <%= flash[:warning] %>
    </div>
  </div>
<% end %>
<%= form_tag cards_path, :class => 'form' do %>
<%  cards = [{ name: "AS", location: "deck", status: 1, cardFront: "&#127137", tablename: @current_user.tablename},
  { name: "2S", location: "deck", status: 1, cardFront: "&#127138", tablename: @current_user.tablename},
  { name: "3S", location: "deck", status: 1, cardFront: "&#127139", tablename: @current_user.tablename},
  { name: "4S", location: "deck", status: 1, cardFront: "&#127140", tablename: @current_user.tablename},
  { name: "5S", location: "deck", status: 1, cardFront: "&#127141", tablename: @current_user.tablename},
  { name: "6S", location: "deck", status: 1, cardFront: "&#127142", tablename: @current_user.tablename},
  { name: "7S", location: "deck", status: 1, cardFront: "&#127143", tablename: @current_user.tablename},
  { name: "8S", location: "deck", status: 1, cardFront: "&#127144", tablename: @current_user.tablename},
  { name: "9S", location: "deck", status: 1, cardFront: "&#127145", tablename: @current_user.tablename},
  { name: "10S", location: "deck", status: 1, cardFront: "&#127146", tablename: @current_user.tablename},
  { name: "JS", location: "deck", status: 1, cardFront: "&#127147", tablename: @current_user.tablename},
  { name: "QS", location: "deck", status: 1, cardFront: "&#127149", tablename: @current_user.tablename},
  { name: "KS", location: "deck", status: 1, cardFront: "&#127150", tablename: @current_user.tablename},
  { name: "AH", location: "deck", status: 1, cardFront: "&#127153", tablename: @current_user.tablename},
  { name: "2H", location: "deck", status: 1, cardFront: "&#127154", tablename: @current_user.tablename},
  { name: "3H", location: "deck", status: 1, cardFront: "&#127155", tablename: @current_user.tablename},
  { name: "4H", location: "deck", status: 1, cardFront: "&#127156", tablename: @current_user.tablename},
  { name: "5H", location: "deck", status: 1, cardFront: "&#127157", tablename: @current_user.tablename},
  { name: "6H", location: "deck", status: 1, cardFront: "&#127158", tablename: @current_user.tablename},
  { name: "7H", location: "deck", status: 1, cardFront: "&#127159", tablename: @current_user.tablename},
  { name: "8H", location: "deck", status: 1, cardFront: "&#127160", tablename: @current_user.tablename},
  { name: "9H", location: "deck", status: 1, cardFront: "&#127161", tablename: @current_user.tablename},
  { name: "10H", location: "deck", status: 1, cardFront: "&#127162", tablename: @current_user.tablename},
  { name: "JH", location: "deck", status: 1, cardFront: "&#127163", tablename: @current_user.tablename},
  { name: "QH", location: "deck", status: 1, cardFront: "&#127165", tablename: @current_user.tablename},
  { name: "KH", location: "deck", status: 1, cardFront: "&#127166", tablename: @current_user.tablename},
  { name: "AD", location: "deck", status: 1, cardFront: "&#127169", tablename: @current_user.tablename},
  { name: "2D", location: "deck", status: 1, cardFront: "&#127170", tablename: @current_user.tablename},
  { name: "3D", location: "deck", status: 1, cardFront: "&#127171", tablename: @current_user.tablename},
  { name: "4D", location: "deck", status: 1, cardFront: "&#127172", tablename: @current_user.tablename},
  { name: "5D", location: "deck", status: 1, cardFront: "&#127173", tablename: @current_user.tablename},
  { name: "6D", location: "deck", status: 1, cardFront: "&#127174", tablename: @current_user.tablename},
  { name: "7D", location: "deck", status: 1, cardFront: "&#127175", tablename: @current_user.tablename},
  { name: "8D", location: "deck", status: 1, cardFront: "&#127176", tablename: @current_user.tablename},
  { name: "9D", location: "deck", status: 1, cardFront: "&#127177", tablename: @current_user.tablename},
  { name: "10D", location: "deck", status: 1, cardFront: "&#127178", tablename: @current_user.tablename},
  { name: "JD", location: "deck", status: 1, cardFront: "&#127179", tablename: @current_user.tablename},
  { name: "QD", location: "deck", status: 1, cardFront: "&#127181", tablename: @current_user.tablename},
  { name: "KD", location: "deck", status: 1, cardFront: "&#127182", tablename: @current_user.tablename},
  { name: "AC", location: "deck", status: 1, cardFront: "&#127185", tablename: @current_user.tablename},
  { name: "2C", location: "deck", status: 1, cardFront: "&#127186", tablename: @current_user.tablename},
  { name: "3C", location: "deck", status: 1, cardFront: "&#127187", tablename: @current_user.tablename},
  { name: "4C", location: "deck", status: 1, cardFront: "&#127188", tablename: @current_user.tablename},
  { name: "5C", location: "deck", status: 1, cardFront: "&#127189", tablename: @current_user.tablename},
  { name: "6C", location: "deck", status: 1, cardFront: "&#127190", tablename: @current_user.tablename},
  { name: "7C", location: "deck", status: 1, cardFront: "&#127191", tablename: @current_user.tablename},
  { name: "8C", location: "deck", status: 1, cardFront: "&#127192", tablename: @current_user.tablename},
  { name: "9C", location: "deck", status: 1, cardFront: "&#127193", tablename: @current_user.tablename},
  { name: "10C", location: "deck", status: 1, cardFront: "&#127194", tablename: @current_user.tablename},
  { name: "JC", location: "deck", status: 1, cardFront: "&#127195", tablename: @current_user.tablename},
  { name: "QC", location: "deck", status: 1, cardFront: "&#127197", tablename: @current_user.tablename},
  { name: "KC", location: "deck", status: 1, cardFront: "&#127198", tablename: @current_user.tablename},
  { name: "RJ", location: "deck", status: 1, cardFront: "&#127167", tablename: @current_user.tablename},
  { name: "BJ", location: "deck", status: 1, cardFront: "&#127183", tablename: @current_user.tablename},]%>

 <% cards.each do |card|%>
  <%if !(params[:checkbox].nil?) %>
    <%key_arr = params[:checkbox].keys%>
    <%if key_arr.include?(card[:name]) %>
      <%   card[:location] = "Out of Play" %>
      <%   card[:status] = 0 %>
      <% end %>
    <% end %>
  <% Card.create!(card) %>
  <%end%>

  <%= label :card, :tablename, name: @current_user.tablename, :class => 'col-form-label' %>
  <%= submit_tag "#{@current_user.tablename}" %>
<% end %>

Team4_SELT2020-main/app/views/cards/remove_cards.html.erb
<h1>Which card(s) would you like to remove?</h1>
<%= form_tag cards_cards_to_remove_path do %>

  <table class="table table-striped col-md-12" id="cards">
    <thead>
      <tr>
        <th>Card</th>
        <th>Name</th>
        <th>Select</th>
      </tr>
    </thead>
    <tbody>
      <% @cards.each do |card| %>
        <tr>
          <td>
            <%= card.cardFront.html_safe %>
          </td>
          <td>
            <%= card.name %>
          </td>
          <td>
            <%= check_box_tag "checkbox[#{card[:id]}]" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>


  <%= submit_tag 'Remove card(s)', :id => 'cards_button', :class => 'btn btn-primary'%>
  <%= link_to 'Return to game', cards_path, :class => 'btn btn-primary' %>
<% end %>