Team4_SELT2020-main/config/routes.rb
Rails.application.routes.draw do

  resources :cards, :tables, :users, :sessions
  post 'cards/play_card'
  post 'cards/draw_card'
  post 'cards/reset_card'
  post 'cards/reset_game'
  post 'cards/select_card'
  post 'cards/pass_card'
  post 'cards/recard_card'
  post 'cards/take_from_board'
  post 'cards/leave_game'
  post 'cards/discard_card'
  post 'cards/recover_discard'
  root 'tables#index'
  post 'users/assign_current_user_table'
  post 'cards/discard_cards'
  get 'cards/discard_cards'
  post 'cards/cards_to_discard'
  get 'cards/remove_cards'
  post 'cards/cards_to_remove'
  match '/login', to: 'sessions#new', via: :get
  match '/login_create', to: 'sessions#create', via: :post
  match '/logout', to: 'sessions#destroy', via: :delete

end

Team4_SELT2020-main/app/models/user.rb
#require 'bcrypt's
class User < ActiveRecord::Base
  belongs_to :table
  #include BCrypt
  has_secure_password
  validates :name, presence: true, length: {maximum: 50, minimum: 1}
  validates :password_digest, presence: true

  #  def user_params
  #  params.require(:user).permit(:name, :password).merge(session_id: SecureRandom.base64)
  #end

  def self.create_user!(params)

    puts("this is pass #{Digest::SHA2.hexdigest(params[:user][:password_digest])}")
    #puts ("before #{params[:user][:password]}")
    #puts("password #{Digest::SHA2.hexdigest(params[:user][:password])}")
    #User.create!(params.require(:user).permit(:name, Digest::SHA2.hexdigest(:password_digest.to_s)).merge(session_token: SecureRandom.base64))
    #User.create!(params.require(:user).permit(:name, :password).merge(session_token: SecureRandom.base64))
    User.create(tablename: params[:user][:tablename], name: params[:user][:name], password_digest: Digest::SHA2.hexdigest(params[:user][:password_digest]), session_token: SecureRandom.base64)
  end
end

Team4_SELT2020-main/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def user_params
    params.require(:user).permit(:tablename)
  end
  def new
    # default: render 'new' template

  end
  def show
    id = params[:id] # retrieve movie ID from URI route
    @user = User.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end
  def wel
  end
  def update
    @user = User.find params[:id]
    if (@user.update_attributes(user_params))
      flash[:warning] = "#{@user.name} updated tablename to #{@user.tablename}."
      redirect_to user_path(@user)
    else
      flash[:warning] = "tablename could not be updated: " +
        @user.errors.full_messages.join(",")
      render 'edit'
    end
  end
  def create

     if User.exists?(['name LIKE ?',"%#{params["user"]["name"]}"])
      flash[:notice] = "Sorry, this users-id is taken. Try again."
      redirect_to new_user_path
     else
       params[:tablename] = "Table 1"
      @users = User.create_user!(params)  #User.create!(user_params)
      flash[:notice] = "Welcome #{@users.name}. Your account has been created."
      redirect_to login_path
    end
  end
  def edit
    @tables = Table.all
    @user = User.find params[:id]
  end
  def assign_current_user_table
    @user = User.where(name: @current_user.name).first
    @user.update(tablename: params[:user])
    redirect_to tables_path
  end

end

Team4_SELT2020-main/app/views/users/edit.html.erb
<% if flash[:notice] %>
  <div class="alert alert-danger">
    <div class="message" id="notice">
      <%= flash[:notice] %>
    </div>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger">
    <div class="flashMessage" id="warning">
      <%= flash[:warning] %>
    </div>
  </div>
<% end %>
<%if !@tables.empty? %>
<h1>Select Table you would like to join</h1>
<%grouped_options = [] %>
<% @tables.each do |table|%>
  <% grouped_options << table.tablename %>
<% end %>
<%= form_tag user_path(@user), :method => :put do %>
  <%= label :user, :tablename, 'Table name:', :class => 'col-form-label tablelb' %>
  <%= select :user, :tablename, grouped_options.each {|table| table}, {}, {:class => 'form-control col-1 tablenm'} %>
  <br/>
  <%= submit_tag 'Choose Table', :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', tables_path, :class => 'btn btn-secondary' %>
<% end %>
<%else %>
  <%= link_to 'Return there are no Tables', tables_path, :class => 'btn btn-secondary' %>
<%end %>

Team4_SELT2020-main/app/views/users/new.html.erb
<h1>Sign-up</h1>
<% if flash[:notice] %>
  <div class="alert alert-danger">
    <div class="message" id="notice">
      <%= flash[:notice] %>
    </div>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger">
    <div class="flashMessage" id="warning">
      <%= flash[:warning] %>
    </div>
  </div>
<% end %>
<%= form_tag users_path, :class => 'form' do %>
  <%= label :user, :name, 'Name', :class => 'col-form-label' %>
  <%= text_field :user, 'name', :class => 'form-control' %>
  <%= label :user, :password_digest, 'Password', :class => 'col-form-label'  %>
  <%= password_field :user, 'password_digest', :class => 'form-control' %>

  <br>
  <%= submit_tag 'Create my Account', :id => 'signupCreate' , :class => 'btn btn-primary' %>
  <%= link_to 'Cancel', login_path, :class => 'btn btn-secondary cancelbtn' %>
<% end %>

Team4_SELT2020-main/app/views/users/show.html.erb
<% if flash[:notice] %>
  <div class="alert alert-danger">
    <div class="message" id="notice">
      <%= flash[:notice] %>
    </div>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger">
    <div class="flashMessage" id="warning">
      <%= flash[:warning] %>
    </div>
  </div>
<% end %>
<!--  app/views/users/show.html.erb -->
<h3>Details about <em><%= @user.name %></em></h3>
<ul id="details">
  <li>
    Table Name:
    <%= @user.tablename %>
  </li>
</ul>
<div class="row">
  <%= link_to 'Choose Table', edit_user_path(@user), :class => 'btn btn-primary col-2' %>
  <%= link_to 'Back to table', tables_path, :class => 'btn btn-primary col-2' %>
</div>